services:
  api:
    build: .
    container_name: loan-api-${ENV_NAME}
    env_file:
      - ${ENV_FILE}
    environment:
      FLASK_ENV: ${FLASK_ENV}
      LOG_LEVEL: ${LOG_LEVEL}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "${API_PORT}:8000"
    volumes:
      - .:/app${DEV_MOUNT}
    deploy:
      resources:
        limits:
          cpus: "${API_CPU_LIMIT}"
          memory: "${API_MEM_LIMIT}"

  db:
    image: postgres:16
    container_name: loan-db-${ENV_NAME}
    env_file:
      - ${ENV_FILE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  reverse-proxy:
    image: nginx:stable
    container_name: loan-nginx-${ENV_NAME}
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: loan-prometheus-${ENV_NAME}
    depends_on:
      - api
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.0.0
    container_name: loan-grafana-${ENV_NAME}
    depends_on:
      - prometheus
    ports:
      - "3000:3000"


volumes:
  db-data-dev:
  db-data-staging:
  db-data-prod:
