events {}

http {
  server {
    listen 443 ssl;
    server_name branchloans.com;

    ssl_certificate     /etc/nginx/certs/branchloans.crt;
    ssl_certificate_key /etc/nginx/certs/branchloans.key;

    location / {
      proxy_pass http://api:8000;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;
    }
  }

  server {
    listen 80;
    server_name branchloans.com;
    return 301 https://$host$request_uri;
  }
}
